### ISSUE TITLE
new auth flow implementation from new design

### ISSUE THREAD

**Issue by yokwejuste** [unstructuredstudio/zubhub#1081]
From the new auth flow provided on the design we should implement some changes on the backend to match all this data.
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/27674325-bb78-4d1f-9fc7-1160160cf58a)
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/60eb957d-a09e-410d-aaed-ea01e45e49d9)
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/803118d1-84fb-4610-8d8a-de3896392b8b)

**Comment by NdibeRaymond** [comment]
should add a description that explains it (maybe add the images of the auth flow design or link to them)

**Comment by NdibeRaymond** [comment]
For this I think on the backend we need to change two files (maybe three or more if you add comment changes):
1. zubhub_backend/zubhub/creators/serializers.py
    CustomRegisterSerializer:
   * add tag field
   * validate the tag received


2. zubhub_backend/zubhub/creators/adapter.py
    CustomAccountAdapter
    * get the tag string, get the corresponding creatortag here and set it
    * if creatortag is staff you need to set creator.is_staff = True too
    * do these before creator.save()

do not touch the tasks.py or signals.py since The CreatorTag operation in signals just helps to make sure that when you create a user without specifying a CreatorTag (or somehow remove all of a creators tag) it defaults to "creator"

Also you might need to update RegisterCreatorAPIView top comment by adding the tag field there.

**Comment by coderatomy** [comment]
I think there is some duplication here

**Comment by coderatomy** [comment]
Related to https://github.com/unstructuredstudio/zubhub/issues/1021
