### ISSUE TITLE
Fix all console errors

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#165]
There are many console errors in the app currently. 

<img width="500" alt="Screen Shot 2021-05-25 at 5 39 17 PM" src="https://user-images.githubusercontent.com/288353/119593401-c3a04b80-bd8e-11eb-8e83-8ca69b1927b7.png">

**Comment by NdibeRaymond** [comment]
Ok, came around to this one and we have some issues here. 

* For the 404 error in staff pick request, that is deliberate as 404 means that the resources we are trying to fetch is not found and it goes away when we add a staff pick. The reason it shows up as error here is a long standing bug that has been reported and acknowledged by several browser creators (see:  https://bugs.chromium.org/p/chromium/issues/detail?id=124534). The only way to fix this right now is through personal user preference settings on each browser (impractical) or by using a different https status code (like 204), but that is wrong because each status code is meant for a purpose and 404 there is exactly being used as it should. That being said, I can change it to another status code to make the red disappear completely (even when there is no staff pick).

* All other warnings we are seeing are a bit outside our control to tackle because they originate from google servers. To verify my claim, open the site on a chrome browser and observe that the errors are not there (google handled them internally in chrome). The warnings originate from, (1) google tracker script, and (2) our youtube and other google related imbedding. To fix the tracking warning, the only way I see right now is to remove the tracker entirely since that piece of code comes from google itself. Then their is the more difficult issue of iframe embedding warnings. It is not as a result of the way we handle the embedding, it is a problem with the way the google part of the code works. Again for this one, to completely fix it, we might have to start looking at maybe handling our videos ourselves. The good news is that this is not dangerous, see this issue for more clarification https://www.reddit.com/r/firefox/comments/fpptyj/firefox_content_security_policy_console_output/. This same issue of embedding videos is also the reason for issue #180, see  https://support.google.com/drive/forum/AAAAOxCWsTofrgeyv07B0s/?hl=en&gpf=%23!topic%2Fdrive%2Ffrgeyv07B0s%3Bcontext-place%3Dforum%2Fdrive

**Comment by tuxology** [comment]
@NdibeRaymond 

> For the 404 error in staff pick request, that is deliberate as 404 means that the resources we are trying to fetch is not found and it goes away when we add a staff pick.

So the first point above can probably be solved by creating an API call which checks a if staff pick is enabled (parsing a boolean return) instead of trying to fetch it and expecting 404. I think this will solve the 404 issue. For now, we can remove this from release blocker but this I think would be a correct way to do it. We can also ask Chaitanya

> All other warnings we are seeing are a bit outside our control to tackle because they originate from google servers. To verify my claim, open the site on a chrome browser and observe that the errors are not there (google handled them internally in chrome). The warnings originate from, (1) google tracker script, and (2) our youtube and other google related embedding. To fix the tracking warning, the only way I see right now is to remove the tracker entirely since that piece of code comes from google itself. Then their is the more difficult issue of iframe embedding warnings. 

Yes, your observations are valid. We can't remove google tracker for now. We will see how to avoid this or if there is a way around it. if not, we leave it as is. Same for iframes. We leave them for now - I know we should move towards hosting or handling these ourselves. This would be a later job I think. I think we should not block our release due to this.
