### ISSUE TITLE
Some projectvideos don't play in mobile view

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#180]
### Steps to reproduce

1. Open the following link in mobile view or on a mobile phone: https://zubhub.unstructured.studio/projects/61045c12-6eae-4678-abda-4f62161a2a8a
2. Click Play button and observe

### Observed Outcome
Video does not play and shows this error in console:
![image](https://user-images.githubusercontent.com/3373857/120194473-7ed34500-c1d2-11eb-8601-bebe2e61c5db.png)

### Expected Outcome
Video should play as expected

**Comment by NdibeRaymond** [comment]
Ok @tuxology , I need more context in other to reproduce this one. I tried it on like four browsers now and only saw this issue with brave because it has something like an inbuilt vpn. Are you using a vpn of some kind? what browser are you using? and when you say mobile view, you mean when the site is opened on mobile phone or when you open the debugger and reduce the screen-size to mobile?

**Comment by tuxology** [comment]
@NdibeRaymond  I first tested this on Firefox and changed view to "mobile". And also tested on Safari on an iPhone. Can successfully reproduce this. I am not using any VPN on either phone or desktop

**Comment by NdibeRaymond** [comment]
Ok after some researches, it seems like this is a bigger issue than we anticipated (see https://support.google.com/drive/forum/AAAAOxCWsTofrgeyv07B0s/?hl=en&gpf=%23!topic%2Fdrive%2Ffrgeyv07B0s%3Bcontext-place%3Dforum%2Fdrive). Basically, this issue is something that has to do with a problem from google's end of the spectrum. It works on most desktops and on chrome mobile browser, but doesn't work on some other ones like safari and firefox. We might have to start looking at in-house video handling as there is no way to know when google is fixing this on their own end.

**Comment by tuxology** [comment]
Oh noes! Ok - this is very interesting. If we can't fix it for now, lets just inform users to click and redirect to to the other website. I think thes can be done by just showing a small "text notification" above video if the browser detected is mobile firefox or safari. Most of our users won't have Firefox or have iPhone for now I think so we are Ok for first version of launch

**Comment by NdibeRaymond** [comment]
> Oh noes! Ok - this is very interesting. If we can't fix it for now, lets just inform users to click and redirect to to the other website. I think thes can be done by just showing a small "text notification" above video if the browser detected is mobile firefox or safari. Most of our users won't have Firefox or have iPhone for now I think so we are Ok for first version of launch

Yeaaa, that's something we can do. That is the only alternative I can see for now.
