### ISSUE TITLE
Improve the UX around tags

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#200]
This feature enhancement consists of two parts:

- How can we make it more clear what tags mean?
- How can we improve the UX around tags. First, we are expecting users to read the help text and understand that they need to enter a comma after every tag they insert. I think it is not the most intuitive design. Second, using a comma at the end of a word so it turns into a tag is confusing. Let's say I have entered one word and entered a comma, and it turns into a tag. Now I want also to add a second tag. It is not immediately apparent here that we need to put a comma because you don't usually do that when writing a sentence with comma-separated values. Instead of a comma, I wonder if we should support the enter key.

**Comment by srish** [comment]
I've made some adjustments to the task title and description

**Comment by amyra98** [comment]
Can you please assign me this issue @srish

**Comment by yaya-mamoudou** [comment]
Hello @srish. I think support for Enter key should be made because, with that, it will be easier an simpler for the user. I think that is what most websites use. Comma has been proven to more more complex but most people intuitively hit enter after entering a word

**Comment by yaya-mamoudou** [comment]
Some other applications use space but that will be for single word tags.

**Comment by Critic-A** [comment]
Hi @srish 
I'd like to contribute to this issue.

Regarding "How can we make it more clear what tags mean?" , I suggest the following
- Moving up this field and placing it after the user enters the description. This makes it more intuitive
- We can suggest tags based on the name and description of the project 
Eg- If the project name is “Maintaining social distancing during Covid -19 pandemic” , there should be an automatic suggestion for the ‘Covid-19’ tag without the user having to type anything in the text box.
This makes the purpose much more clear.

Regarding "Improving the UX of tags"
We should definitely prefer the Enter key support.

**Comment by Critic-A** [comment]
> 

I'd like to be assigned to this issue

**Comment by satyamksharma** [comment]
Hi there, I'm an outreachy applicant and would love to work on this issue, so please assign me.

**Comment by DesignTaicho** [comment]
Hello @srish @tuxology.
I created an account on the zubhub website and created a project. I noticed the tags issue because I also found it difficult to use.

  1. Problem: 
• There was no way to know what the available tags were. Since it was not available in a drop down option.
•  it wasn’t indicated or tagged as an optional question also.

   2. My objectives;
• Redesign the tag feature and make it easier for users to understand and use.
• Make the design straightforward too and the text short and understandable. 


  3. What I did to solve the problem;
• I made sure all tags were available on screen, so users could know what to pick from.
• I made sure the tags were in a clickable button format also, So when clicked could be indicated there on the page for the user to notice.
• I made sure the button only appeared when the tags field is tapped on, so it wouldn’t confuse the users and clutter the page.
• I also added a text that would help users understand what they’re expected to do and the purpose of the tags.
• I added an “optional cue” to inform users of the question’s status.

I redesigned two pages on Figma to show my solution. 

First page: The first page shows the project creation feature I worked on, where the creation process was divided into pages in consideration of the law of similarity and priority, the goal was to reduce the overwhelming content which was on the site in a single page. The aim of this was to also inform the user of their progress while they created their projects. If you check clearly you can notice the optional cues and the texts which helps explain to the users how they could pick the tags 

![B27ACD39-645C-4EF7-AAF9-BFE7643EA401](https://user-images.githubusercontent.com/105350520/224116131-c531225d-455a-40ff-b3b8-89d79e26adf2.jpeg)

Second page: The second pages shows the continuation of the first page. This page shows what happens next when the users taps on the tag field. A drop down of all the tags would appear underneath the field in clickable buttons which the user can then choose from. When selected the button changes color to indicate to the user that he/she had selected the tag. The then selected tag will now appear in the text field above.  I also added a text that clarifies that the user can pick more than one tag at the same time .

![57BFD45E-3B8D-43DB-8F88-E42B2986D627](https://user-images.githubusercontent.com/105350520/224118063-be1456d6-c7e6-40f1-86c4-476b267066ae.jpeg)

Thank you for going through this. I await your helpful feedbacks as it would help me proffer better solutions to this problem. 

@srish @tuxology Please what do you think about this ? 


Here’s the Figma link of this work, which you will find under tags in this file : 
https://www.figma.com/file/pxqJTdTdRSHT2rjvN5vrch/Zubhub?t=PTVacMtCh0YweIPh-6

**Comment by tuxology** [comment]
@Fidausym and @Critic-A  I like your idea, this does requires some way to understand some possible tags and propose them to users - maybe via understanding previous tags, the descriptions that users added and then showing them some options relevant for them. Could be some work in backend to do this. 

@yaya-mamoudou valid point on Enter key as well. Lets keep in iterating more. Another thing to think about is that what is the point of "categories" then? They are very close to "tags". Should we allow categories to be picked from selecting 1 out of 10 pre-defined pills and then tags can be another set of pills that are auto suggested (also selectible)? Should we think about how hashtags are used in social media? Think a bit more and let us know.

**Comment by Temabo** [comment]
Hello @srish @tuxology @darechan 
 On improving the UX around tags:
To make it more clear what tags mean, we can add a brief description in the input field. This description would explain the purpose of the tag. Also, we can include suggested tags underneath the input field so that the kids can easily select them. 
![Frame 63 (1)](https://user-images.githubusercontent.com/105416140/224428195-3de46323-5aae-471e-84e3-5f827654bb9e.png)


2. Remove the need for commas: Instead of requiring users to Enter a comma after every tag, we could allow them to simply enter each tag and press the enter key. Also to make it more apparent that the user is entering a tag, we could highlight the tag after it has been entered. We can make the tag filled instead of outline.
![Frame 64](https://user-images.githubusercontent.com/105416140/224427677-89b2d24e-2022-494d-9561-e3120e431b4e.png)

3. Auto-suggest tags: As the user types in the tag field, we could provide auto-suggestions for commonly used tags. This would make it easier for the user to select the appropriate tag and reduce the likelihood of typos or misspellings.
![Frame 65](https://user-images.githubusercontent.com/105416140/224429683-ec0d86a5-5bcb-413f-926b-b3bd6605ca73.png)
Please let me know your feedback

**Comment by DesignTaicho** [comment]
@tuxology 

1• I think users should be allowed to pick more than one pill/label in the categories section, and for the tags, auto suggestion will list out all or recent tags associated or related to the categories the users had chosen. 

2• While using pills/ label feature. They’ll be no need for the use of comma’s or enter key. All users have to do is click on one or more of the suggested pill/ label and it’ll appear in the field it was requested in. It’ll also appear in the field  in a pill/label form with an “x” icon beside it whose function would be to remove the pill/label if the user changes his/her mind. Aside it appearing in the text field, any pill/label tapped on would change to a filled color to indicate to the user that he/she had selected it. 

@tuxology @srish what do you think?

**Comment by DesignTaicho** [comment]
@Temabo . Good work 👏🏽. Your work makes it easier for users to understand what they’re expected to do. The (maximum of 6) will let users understand that they can only pick six tags and not just one.

**Comment by Temabo** [comment]
> @Temabo . Good work 👏🏽. Your work makes it easier for users to understand what they’re expected to do. The (maximum of 6) will let users understand that they can only pick six tags and not just one.

Yes it does. Thanks! @Fidausym

**Comment by srish** [comment]
Closing it for now as new UX around project creation addresses this partially.
