### ISSUE TITLE
Improve the UX around categories

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#201]
It is not immediately clear right now which category option one should pick for their project. Instead of a dropdown, I wonder if we show a grid of options in the form of grayed-out buttons with images illustrating each category, which might be more helpful for the user. It might also be beneficial to seek a UX designer's input on whether or not we should allow picking multiple categories.

**Comment by alicendeh** [comment]
Hi @srish please can i work on this?

**Comment by srish** [comment]
Okay, assigned! Allowing to choose multiple categories is definitely needed, but when adding more category options is concerned, I don't have good ideas about what we can include. But, yes, the former needs work.

**Comment by alicendeh** [comment]
Hello, @srish I understand the aspect of picking multiple categories. But please can you explain to me the add more category options?

**Comment by srish** [comment]
@alicendeh You can ignore that part for now as it requires someone from our team to propose the new categories to add to the list :) But, allowing to pick multiple categories is still valid.

**Comment by alicendeh** [comment]
Please I'd like to ask @srish  since multiple categories will have to be uploaded to the server, does the current server side code allows an array of categories to be sent?

**Comment by srish** [comment]
@alicendeh I am not sure of the technical implementation. Maybe @NdibeRaymond and @tuxology have an insight here.

**Comment by alicendeh** [comment]
> @alicendeh I am not sure of the technical implementation. Maybe @NdibeRaymond and @tuxology have an insight here.

@NdibeRaymond  and @tuxology. Please your response is needed here

**Comment by srish** [comment]
I've made minor changes to the title and description of the original task.

**Comment by amyra98** [comment]
Can you please assign me these issue and tell me in detail what do i have to do? @srish

**Comment by ferindesigns** [comment]
Good afternoon @srish. Please could I be assigned this issue?

**Comment by DesignTaicho** [comment]
Hello @srish  @tuxology 
I created an account on the zubhub website and created a project. I noticed the category options needed a change. I wanted people to be able to select the categories without scrolling down to find them, something more interactive and fun.

Important note : from what I read earlier about the multiple selection issue, This solution can easily allow users to pick multiple categories because all they have to do is tap on the categories and they’ll appear in the categories fields.

*My thoughts on the category option;
1. Problem:
• it looked too professional and boring for a child website 
• it wasn’t indicated or tagged as an optional question also.

2. My objectives;
• Redesign the category feature and make it easier for users to understand and use.
• Make the design fun and trendy and the text short and understandable.
• Fly it off as “optional” too

3. What I did to solve the problem;
• I made sure all the categories were available on screen, so users could know what to pick from.
• I made sure the categories were in a clickable button format also, So when clicked could be indicated there on the page for the user to notice.
• I made sure the button only appeared when the category field is tapped on, so it wouldn’t confuse the users and clutter the page.
• I also added a text that would help users understand what they’re expected to do and the purpose of the tags.
• I added an “optional cue” to inform users of the question’s status.

I redesigned two page on Figma to show my solution.

First page: The first page shows the project creation feature I worked on, where the creation process was divided into pages in consideration of the law of similarity and priority, the goal was to reduce the overwhelming content which was on the site in a single page. The aim of this was to also inform the user of their progress while they created their projects. If you check clearly you can notice the optional cues and the texts which helps explain to the users how they could pick the tags

![B97B73FB-D0D7-4CFD-91EB-4845F902F49F](https://user-images.githubusercontent.com/105350520/224126986-eda12081-f3d9-4ef1-8ae5-ed1cba90247d.jpeg)


Second page: The second pages shows the continuation of the first page. This page shows what happens next when the users tap on the category field. A drop down of all the categories  would appear underneath the field in clickable buttons which the user can then choose from. When selected the button changes color to indicate to the user that he/she had selected the category. The then selected tag will now appear in the text field above. I also added a text that clarifies that the user can pick just one category. 

![3B656018-3730-4A8E-879A-E7338B17ECE1](https://user-images.githubusercontent.com/105350520/224127937-56506c4b-5578-457f-a1e8-4c445a9474dc.jpeg)




Important note : from what I read earlier about the multiple selection issue, This solution can easily allow users to pick multiple categories because all they have to do is tap on the categories and they’ll appear in the categories fields.


Thank you for going through this. I await your helpful feedbacks as it would help me proffer better solutions to this problem.

@srish  @tuxology  Please what do you think about this ?

Here’s the Figma link of this work, which you will find under tags in this file :
https://www.figma.com/file/pxqJTdTdRSHT2rjvN5vrch/Zubhub?t=PTVacMtCh0YweIPh-6

**Comment by srish** [comment]
Recent UX improvements related to project creation addresses this.
