### ISSUE TITLE
Signup works only when phone number is provided

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#206]
Even after filling the sign up form properly, upon clicking "Sign Up", nothing happens on mobile

**Comment by NdibeRaymond** [comment]
strange. looking into this now

**Comment by NdibeRaymond** [comment]
Ok, this seems to be from a merged change that broke the functionality. Signup works only when phone number is provided. Fixing that now. If you can confirm that this is the same issue you encountered, I can go ahead and give the issue a more suitable title

**Comment by tuxology** [comment]
Ok, yes, its the same issue! thanks a lot for verifying 👍🏽

**Comment by NdibeRaymond** [comment]
Got around to fixing this. Can't create a PR though since the problem was with the database. We removed unique constraint from the model to allow for saving blank phone numbers but it wasn't completely removed from the database (still remained in the table index), that was what was causing the error. Fixed it now and already tested it, it works now.

**Comment by NdibeRaymond** [comment]
closing this issue now, we can open it again if there is any other reason to
