### ISSUE TITLE
Auto translation of whole ZubHub in multiple languages

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#222]
We need this feature to support translation of static as well as dynamic data .
* Static (e.g., header on home page, nav bar titles, description in about page, etc.)
* Dynamic (e.g., projects, comments, user profile, etc.)

Perhaps something of this sort like Facebook does:
![Screen Shot 2021-07-03 at 11 30 46 AM](https://user-images.githubusercontent.com/288353/124363778-212b8180-dbf2-11eb-84dd-0983dc482962.png).

Currently, we are handling this well for some elements (buttons, footer menu items). Ideally, the app should support for translating content for every single element in multiple languages.

**Comment by Deepthi562** [comment]
@srish i think we can use google translator API for this. Can u assign this to me? Thank you.

**Comment by srish** [comment]
@Deepthi562 This is a big task. I would encourage you to look at more small and easy tasks first.

**Comment by iamhks** [comment]
Hi @srish @tuxology  I would like to take on this issue. Please assign it to me.

**Comment by iamhks** [comment]
@tuxology Is it okay if we use Google Translate for the translation of dynamic content? How do you want me do proceed:
1) Do you want me to create another dropdown for google translate on the site?
2) Use the existing dropdown to incorporate google translate but I guess this will nullify our work on hindi translation till now!

**Comment by tuxology** [comment]
I am thinking about this as well, I think if we use Google Translate, it  will also translate the content submitted by users. Is that what we expect? I think not yet. Can you review some other approaches how other websites handle translations?

**Comment by iamhks** [comment]
Sure, I will explore possible approaches. Meanwhile,

> I am thinking about this as well, I think if we use Google Translate, it will also translate the content submitted by users. Is that what we expect? I think not yet. 

@tuxology If that is not what we expect then what did @srish exactly mean to have translation for dynamic content?

Update: I looked into it and the max I can find is interpolation wherein a statement `My name is {user_name}` can be translated to the specific user's name. 
Waiting for your input...

**Comment by benndip** [comment]
Hello, @srish  @tuxology please I have some thoughts and work I've done on this issue, and I would love to be assigned it so I can release a PR ASAP.

I have managed to implement a better way to handle the translation of the whole website using `i18n-js` and `redux`. And I have translated about 70% of the site already on this branch below

[https://github.com/benndip/zubhub/tree/feat-222-Auto-translate-whole-zubhub](url) 

The advantage of using redux is that any component in the app can read the current locale with ease, and we don't need "wrappers" everywhere. We just call it using the `useSelector` hook since it's in the store, and we are using `functional components`. For example if you notice in the video demo below, once you translate from the `Navbar`, you do not need to translate again on the footer because the whole site translates at once. So no need to have a translate dropdown on both `Navbar` and `Footer`

Below is a demo of what I have been able to do. It shows just a few screens for the sake of video size, but I have translated about 70% of them.

https://github.com/unstructuredstudio/zubhub/assets/51094040/bae17f1c-54cd-44a7-ba1c-72605f3f2877

Also, I am using `localStorage` to save what the user chose last time as his language of preference so that if he comes back to the site next time, it will be in the same language that he selected. 

**Here are some ways I think will make this even better**
 - Use Google Cloud translate API from here:  [https://cloud.google.com/translate/docs/reference/rest/v3beta1/projects/translateText](url) to translate `dynamic` data maybe from the backend
 - Read the user's computer language using this [https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language](url)
so that even if the user visits the site for the first time, we will automatically know which language to show the user
