### ISSUE TITLE
Handling incorrect video url

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#223]
Might be in the following project: https://zubhub.unstructured.studio/projects/7a729910-86bd-419a-8fd4-8c9c268d60bd, the student entered an incorrect url. And, so now the message we get as a result of it is "www.youtube.com refused to connect.". Might be we can do some url validation here and show an error message to user as well as a thumbnail for missing videos.

**Comment by NdibeRaymond** [comment]
@srish we are already doing url validation for videos urls, the problem is that there is no way to know if the video id points to an existing video if the submitted url adheres to the correct validation rules. for example https://youtube.com/dlksdjsldklskd is still a valid video url since the format adheres to the url format, however that doesn't mean the video exists in youtube's database.

**Comment by ntungwe-90** [comment]
@NdibeRaymond  how about using the youtube API to perform the validations?

**Comment by srish** [comment]
The project I linked earlier no longer shows the error, and the video renders appropriately. In any case, if there is a way to know if / when an error is generated, we show a custom image to demonstrate the same?
