### ISSUE TITLE
Add notifications model and add/update/delete endpoints

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#284]
## Description

In order for the user to see a list of the notifications they haven't seen we need to store them in a table. 

## Learning objectives

- Creating models in Django
- Creating/testing endpoints

## Todo

- [x] Create notifications model 
- Model should contain notification message, notification recipient, whether it has been viewed or not, Date added
  
- [x] Notification endpoints - Update notification, Delete notification, Get notification by user

## Useful links

- https://www.caktusgroup.com/blog/2019/02/01/creating-api-endpoint-django-rest-framework/

**Comment by NdibeRaymond** [comment]
Since notifications are kind of like a personal experience (my notifications doesn't necessarily need to be the same as yours), I think a better data model is for notifications model to have a one to many relationship with the Creator model (this was actually the intention of the task creator as pointed out by @ajain1921)

Also, since notifications are feedbacks from the system to users based on certain actions that are of interest to the user, I don't think having a "Add new notification" endpoint makes sense. "Update notifications" and "Delete notification" endpoints (or something similar to these) makes more sense because while a user shouldn't be able to notify themselves, they should have the ability to delete notification(s) or mark them as read.

Of course I might be wrong and you have already thought about all of this, so if you have a better data model let's talk about it here so we can model out the exact requirements for acceptance of a PR for this feature.

**Comment by ghost** [comment]
> 
@NdibeRaymond 
I don't understand how the relationship between a Notification and a Creator would be one-to-one. Each Creator can have multiple notifcations in their notification view. For that reason, I was thinking of doing something like `recipient=models.ForeignKey(Creator,...)` in the Notifications model to establish the many-to-one relationship between a Notification and a Creator. Let me know if I'm misunderstanding or missing something but that's where I'm at currently. Here's a sample design of what the Notifications view might look like for reference.

![undstructuredstudio_notifs_hover](https://user-images.githubusercontent.com/24413724/153967614-44ac213c-45c1-42a5-8087-75ba6dc72591.png)

**Comment by NdibeRaymond** [comment]
> > 
> 
> @NdibeRaymond I don't understand how the relationship between a Notification and a Creator would be one-to-one. Each Creator can have multiple notifcations in their notification view. For that reason, I was thinking of doing something like `recipient=models.ForeignKey(Creator,...)` in the Notifications model to establish the many-to-one relationship between a Notification and a Creator. Let me know if I'm misunderstanding or missing something but that's where I'm at currently. Here's a sample design of what the Notifications view might look like for reference.
> 
> ![undstructuredstudio_notifs_hover](https://user-images.githubusercontent.com/24413724/153967614-44ac213c-45c1-42a5-8087-75ba6dc72591.png)

Yes please, it was my fault. It's actually a one to many relationship (correcting that now).

**Comment by srish** [comment]
This task is complete.
