### ISSUE TITLE
Create project button embedded twice on `/profile` page

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#29]
Perhaps, we should remove one of the "Create profile" buttons from the navbar. Maybe there is a reason we have two?

**Comment by NdibeRaymond** [comment]
> Perhaps, we should remove one of the "Create profile" buttons from the navbar. Maybe there is a reason we have two?

Ok, about this, the create project button in the navbar area was a recent addition made so that creators won't have to visit the profile page before they can create a project. I think your observation is valid. Since it is on the navbar, it doesn't need to be in the profile page again. Will removed it
