### ISSUE TITLE
The navigation bar is not sticky when you scroll down

### ISSUE THREAD

**Issue by Francoise02** [unstructuredstudio/zubhub#415]
**Describe the bug**
The navigation bar isn't sticky when you scroll down on the explore ideas page.

**To Reproduce**

1. Go to 'homepage'
2. Click on 'Explore ideas'
3. Scroll down to 'Any project close to the footer'

**Expected behavior**
The navigation bar should stay visible at the top of the page regardless of whether you scroll down.

**Screenshots**
![Screenshot (792)](https://user-images.githubusercontent.com/90447870/163894403-e0361a29-8798-4dc9-b04b-64ab2f42a3cd.png)

![Screenshot (791)](https://user-images.githubusercontent.com/90447870/163894292-d083f37d-9971-4e6f-b62c-cb66facb66e1.png)

**Comment by Francoise02** [comment]
@NdibeRaymond @tuxology I would like to work on this issue.

**Comment by tuxology** [comment]
This issue is not related to the ZubHub application. ZubHub is hosted at zubhub.unstructured.studio. However, there is a task associated with moving these activities to ZubHub application. See https://github.com/unstructuredstudio/zubhub/wiki/Feature-Roadmap-&-Ideas-2022#3-allow-creation-of-learning-activities-on-zubhub-web-app for more info on actual task. Closing this one
