### ISSUE TITLE
Make enhancements to user profiles

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#484]
Currently, each user gets their own public profile when they create an account. Here is an example:https://zubhub.unstructured.studio/creators/suchakra. The public profile currently consists of a basic description of the user, a count of followers, a showcase of projects, and a public comment wall. We wish to enhance the user profile page by adding more engagement features such as statistics (e.g., graph of total projects and views received over time.) and badges (e.g., "project of the week" that the users can showcase. This feature will improve a young creator's public profile and boost their confidence. A good showcase acts as a feedback loop where they would want to engage in more creative projects with their peers and show their profile with more confidence to their teachers.

**Comment by Deepanshu039** [comment]
Greetings @srish , I would like to work on this feature.

**Comment by Deepanshu039** [comment]
I will also update my questions and suggestions to this discussion.

**Comment by Deepanshu039** [comment]
These are the categories I was thinking of in which we can assign badges to the creators: -
1. On the basis of Project count ---> (1+ project, 10+ project, 100+project )
2. On the basis of total views count ---> (1k+ views, 10k+ views, 100k+views)
3. On the basis of the Likes count  ---> ( 100+ likes, 1k+ likes, 10+ likes)
4. On the basis of Comments a creator makes ---> (100+ comments, 500+ comments, 1k+ comments)
5. [optional] On the basis of followers ---> (100+ followers, 1k+ followers , 10k+ followers)

since these are just the categories in which we will assign badges to the creators the actual title which will display on the user profiles will be different. 
The appropriate title can be discussed and can be assigned to the particular count, also the no of counts for a particular count can be increased and decreased as instructed.

I have prepared these two mockups for adding achievements components to the user profile and would really like to get your feedback on this @srish @tuxology .
![Adobe Scan 04-Jun-2022_1](https://user-images.githubusercontent.com/92849065/171985938-42b6f8f5-0e96-4fba-8a15-4854b554faa7.jpg)

since @tuxology  suggests initially we will consider tags for the achievements so I thought of this, later on, these tags will be displayed with the medals or trophies which will be associated with a specific tag.

**Comment by srish** [comment]
@Deepanshu039 The initial design looks great and makes a lot of sense! :-) I also like the placement of achievement box. Sharing a few thoughts:

First on what additional badges to consider besides the one you have already shared:
* On the basis of comments a creator has received
* Project featured by studio / Featured on homepage. For example, see "Projects from our recent creative learning workshops" on the homepage
* Custom badges that studio should be able to award from the backend 
* I think this might be too ambitious for now, but in the future, based on the category someone shares a lot of projects under (let's say "Art," then they can be awarded a badge of an "Artist")

Maybe in the achievements box, we can consider showing not more than 10 badges. And, if there are more badges, then they can be viewed on a separate page. 

Other than these badges, I think we can consider showing a few more statistics:
* Activity log and ability to pick a featured project on ZubHub. See for reference:
https://scratch.mit.edu/users/SrishAkaTux/

* Number of projects, views, date of joining the platform, number of comments received, location. See for reference:
https://www.instructables.com/member/Markus+Opitz/

Maybe based on this comment, think about what is doable in the three months time and propose a modified mockup that I can take a look at. Just a thought, the priority order could be - badges, statistics, activity log, featured project. We don't need to try to complete everything :)

**Comment by Deepanshu039** [comment]
thankyou so much @srish for appreciating the design, first of all, can you plz suggest which mockup we should further proceed with.

**Comment by Deepanshu039** [comment]
for not displaying more than 10+ badges we can simply add a "+more" button, I will soon upload a mockup for this for better clarity.

**Comment by ttseng** [comment]
Following up from the start of our conversation on Friday.  

It's great that you're starting to think about what will motivate people to revisit the site and their profile page.  It might be helpful to list out the intended end goals, which I think would help inform what enhancements you design for the profile page.  For example, some potential goals may be,

A) helping users connect with other community members
B) helping users discover new types of activities / projects 
C) giving users recognition for their efforts

Right now, I think the design suggestion to focus on metrics like view count / # of followers is focused on Goal C, but may not foster goals A and B.  For example, seeing that you have a lot of views on your projects may not in and of itself help you find other people with similar interests, or help you discover new types of activities you haven't considered trying out yet.

I would encourage thinking about goals A and B because when focusing too much on metrics (# of likes, etc.) that may foster an unhealthy relationship with extrinsic motivators.  For example - you may look into Instagram's experiments around hiding the Like count on posts and instead emphasizing who was interacting with posts (https://www.theverge.com/2021/5/27/22456206/instagram-hiding-likes-experiment-results-platformer).  Similarly, to encourage more intentional engagement, Twitter had changed their retweet button from automatically retweeting content to presenting users with a choice for whether to quote retweet and share their own perspectives.

It might also be worth looking into the High Fives system that was recently developed at Primer (a social network for kids) https://primer.com/blog/announcing-high-fives - rather than focusing on likes, they seem to be enabling a more nuanced way to show appreciation.

Generally, I am a fan of more engagement-focused feedback that goes beyond numeric metrics.  To share one example, I often find reactions on Slack to be a really helpful gauge of the way different content is received (for example, seeing that a post shared on Slack has a lot of different reactions shows a different type of engagement than all of the same reaction, like a thumbs up).  I wonder if providing more of a range of expressive feedback might encourage a different type of community than more common metrics like page views/likes.  (for example, if people are able to applaud your work 👏, show that your project inspired them 💡, share that a project made them laugh 😆, etc. you might have a richer set of ways to engage with one another.

**Comment by srish** [comment]
Done via Outreachy - now there is a badges feature and activity log on ZubHub.
