### ISSUE TITLE
Add DarkMode Feature for ZubHub Website

### ISSUE THREAD

**Issue by robinokwanma** [unstructuredstudio/zubhub#590]
**Describe the the feature request**
Zubhub has a very beautiful interface, but adding darkmode option takes it to a whole new level and adds a different feel for users like me who love darkmode.

**Comment by robinokwanma** [comment]
Consider this and assign it to me please @srish

**Comment by darechan** [comment]
Hey @robinokwanma , I believe a dark theme for any project is relatively ambitious, could provide UI mockups for the idea and how do you plan to take that forward so we could have a discussion on this. Also a suggestion to move  this to `featured requests` in the discussion. So that everyone could participate in the same!

**Comment by robinokwanma** [comment]
Hi @darechan  to be clear, i can provide the UI mockups for the idea? or are you interested in making the mockups?  I have no issues moving this to the featured requests section but, i really want to be a part of it. I have some ideas to make it work.

**Comment by darechan** [comment]
@robinokwanma Sure please do provide the UI mock up! A visual look up is always better for understanding.

**Comment by srish** [comment]
This is not on the radar for now.
