### ISSUE TITLE
Our ambassador page redesign and mobile responsiveness

### ISSUE THREAD

**Issue by emteehi** [unstructuredstudio/zubhub#608]
The hierarchy in the ambassador page needs to be worked on.
The contents on the page can be made clearer
The page is not responsive on mobile.
![Screenshot_20230309-000410_Chrome](https://user-images.githubusercontent.com/63165912/223872845-05395f61-8317-4806-8b65-2dc2cbbaf607.jpg)

**Comment by emteehi** [comment]
I'd also redesign the cards.
![Screenshot_20230309-000950_Chrome](https://user-images.githubusercontent.com/63165912/223873491-b94464d7-a5b3-42c3-a3a8-2ee588c2e726.jpg)

**Comment by Temabo** [comment]
Ambassador Page re-design:
I noticed the Hierarchy on this page was poor and the details of the ambassadors were not properly alligned with the card. 
I also redesigned the cards and showed the "public tag" instead of using a web icon which could be confusing
@tuxology @srish Kindly take a look and let me know your feedback so I can commence work on the mobile view and also tab so it is responsive accross all screens
![Ambassador page (1)](https://user-images.githubusercontent.com/105416140/224290723-d348f1ea-4f7c-4345-8d28-7ea9b9eb3d1e.png)

**Comment by Mara-mma** [comment]
@Temabo this is nice. What else are you working on and can we collaborate?

**Comment by Temabo** [comment]
@Mara-mma Thank you, and yes please let's work together on some issues. I have some ideas. I will send a message to you on Zulip.

**Comment by ComradeVedant** [comment]
@emteehi @tuxology hey, I'm an Outreachy applicant, could you assign this issue to me?

**Comment by emteehi** [comment]
@ComradeVedant im working on it already

**Comment by ComradeVedant** [comment]
No one has been assigned so i guess anyone can work on it

**Comment by tuxology** [comment]
Please note, content of this page is pulled from a direct text we input as HTML from backend. We want this page to be editable by the admins hence the design is not uniform. While I like @Temabo 's design ideas, we would not want to implement this for now. Lets keep this open and not proceed on fixing this right away

**Comment by Temabo** [comment]
Alright 👍🏾 @tuxology

**Comment by srish** [comment]
Mobile responsiveness fixed for ambassador page
