### ISSUE TITLE
Feature Request: Ability to Add Custom Tags to Projects

### ISSUE THREAD

**Issue by Burnleydev1** [unstructuredstudio/zubhub#641]
**Describe the the feature request**
I would like to request a new feature that allows me to add custom tags to my projects. Currently, the website provides a set of predefined tags that can be added to a project, but it would be beneficial to allow users to add their own custom tags.

**Comment by EbukaOkoye** [comment]
I want to work on this issue

**Comment by Burnleydev1** [comment]
Hello @EbukaOkoye, I'm sorry I would also love to work on it if approved.

**Comment by tuxology** [comment]
Please edit your issue with a clearer description of what you think is a proposed feature or a bug

**Comment by Burnleydev1** [comment]
Hi @tuxology here is the updated issue

**Comment by tuxology** [comment]
You can add custom tags currently to projects already. The suggestions of tags you get while creating a project is based on tags that were  created by  other users. You can ignore them and create your own as well. Since this is not clear, this might be a UX work as part of #610  more than a feature. Closing this one!
