### ISSUE TITLE
Improve the header design on the landing page

### ISSUE THREAD

**Issue by mehreeee** [unstructuredstudio/zubhub#792]
<img width="2017" alt="Review@2x" src="https://github.com/unstructuredstudio/zubhub/assets/105458062/d95006fa-3635-47b7-9222-afe0fc61ccb4">

1. The Hero Text lacks Hierarchy and the CTA button isn't bold enough to call attention to the user. 
2. The logo and hero text are not aligned vertically
3. The Creator Review section has a visibility issue. The text color and background color do not pass the contrast check.

**Comment by mehreeee** [comment]
@srish @tuxology I have redesigned the hero page to look more visually appealing, using the brand colors and added hierarchy to the text and buttons. Please I would appreciate your feedback and I would continue to redesign other sections to look better.
![Hero](https://github.com/unstructuredstudio/zubhub/assets/105458062/a2b4ca6b-7efb-4941-94b6-9ed6dec9d840)

**Comment by mehreeee** [comment]
@srish @tuxology for the Creator Reviews section, I came up with this. 
![Creator Reviews](https://github.com/unstructuredstudio/zubhub/assets/105458062/9516af07-d60a-4e46-99df-5b8f6445027a)

**Comment by srish** [comment]
Thanks for filing this! Agree with you @mehreeee. Even though we have a design for this already. See frame 1011 in the landing page design here: https://www.figma.com/file/hidnBfP4kNWl7RDxy3aUZI/ZubHub?type=design&mode=designhttps://www.figma.com/file/hidnBfP4kNWl7RDxy3aUZI/ZubHub?type=design&mode=design, the implementation missed out on the details. Also, we would like to use another image which matches with the theme. The current image emphasizes the educator as a "sage on the stage" in a traditional setting instead of a "guide on the side," which is ZubHub's approach to teaching and learning. It would be great to replace it with the following image.

![Family-Values-School-Trip-1kids] (https://github.com/unstructuredstudio/zubhub/assets/288353/88a950f6-858f-4a1a-a50c-46a03e9fd2a4)

It might be good to check with @Faridah-ux on Zulip to obtain the high quality version of the illustration.

Adjusting margins, re-arranging text and changing cover image is what we can focus on as part of this task.

Another small thing - the title "Featured projects" should have same size as other titles. If that can as well be addressed as part of this PR, please :)

**Comment by mehreeee** [comment]
Thank you @srish I will get to it as soon as possible

**Comment by PascalAnuche** [comment]
For the hero section, I improved the header so the users can navigate the landing page easily, and also have two CTA buttons to either Sign-up or Sign in 
This is the figma link:
https://www.figma.com/file/zWHBhu5EnsNJbMi26j1NKb/Outreachy-Zubhub-intern?type=design&node-id=0%3A1&mode=design&t=pmbysZa8yiWtFiEV-1
<img width="1549" alt="Frame 427321226" src="https://github.com/unstructuredstudio/zubhub/assets/101313594/8aafa56d-d4fe-485d-ba7d-e0ac9bbd33d2">

@srish

**Comment by Temabo** [comment]
@srish I got the high quality of the replacement Illustration from figma, this is what it looks like in the design.
![home -_unstructuredstudio](https://github.com/unstructuredstudio/zubhub/assets/105416140/749c1c15-7baa-4472-9597-8e186df0d05b)
https://www.figma.com/file/A1GYQtENXSmPUzB63MTgPj/outreachy?type=design&node-id=563%3A8905&mode=design&t=apIltWVttx97Nt2g-1

**Comment by JulietMadu** [comment]
i was able to fix the alignments on the header page, i improved the colours to make it visible and i added categories to the landing page so as to make it easy to findprojects under the category it falls under. what do you think about it  @srish 
![header redesign](https://github.com/unstructuredstudio/zubhub/assets/128796937/fd52f5bf-2395-4e01-9ed3-c7730566c20f)

**Comment by GloriaKaduru** [comment]
Hello! @srish 

I worked on re-arranging the text and changing the cover image of the landing page. For the header copy, I repositioned the text and edited it quite a bit. Here's what it looks like:
![Hero Page with Old Copy](https://github.com/unstructuredstudio/zubhub/assets/82684587/aedc21aa-65e1-425e-9b2f-264bd89a1977)

I changed the text size of 'Featured Projects' to match with the other header title text sizes on the page, seen here:
![Adjusted Text Size for Featued Projects](https://github.com/unstructuredstudio/zubhub/assets/82684587/86ce4658-0f25-4465-a9c9-fe5f9ee02b52)

Secondly, I tweaked the 'Projects/Activities' section, giving it more space and making it more visually appealing.
![Projects and activities](https://github.com/unstructuredstudio/zubhub/assets/82684587/a94e2615-eeda-43c8-bc16-bb9f50bfd34e)

Lastly, I worked on the copy for the header. The copy we currently use isn't striking enough and doesn't quite tell what the section is about. I came up with new sample copy for both the students landing page as well as the educators/creators. This can be seen here:
![Hero Page with New Copy (For Students)](https://github.com/unstructuredstudio/zubhub/assets/82684587/286d3d3f-90e1-459b-94a8-3bbaafbc55e0)

and here:
![Hero Page with New Copy (For Creators)](https://github.com/unstructuredstudio/zubhub/assets/82684587/2a604b35-79d0-46fa-8a41-697a511f7351)

Look forward to your feedback!  @srish

**Comment by yokwejuste** [comment]
@srish when you validate any of this I'll work on it

**Comment by coderatomy** [comment]
nice work @GloriaKaduru. Your designs are really nice

**Comment by pachougu** [comment]
@srish is this issue closed or can someone still work on it

**Comment by Marhiposa** [comment]
Hi @srish i worked on the header design on the landing page and changed a few things. i replaced the profile logo to SIgn in. i believe the logo is not  necessary for guest users. i personally think the removing the long search button and the projects section will direct users straight to where they need to go , although theres still a search bar should incase a user needs to search. also in the creator section i noticed there wasnt any icon header so i added the icons for direction and easy user satisfaction. pls let me know what you think ?

![landing page (1)](https://github.com/unstructuredstudio/zubhub/assets/146780247/6885bd17-f0bf-40bf-b792-ef7aa4104d01)

**Comment by outcast-02** [comment]
I made a PR and I got to know that I was not supposed to make it( im not sure about it so pardon my mistake .. I am still new and learning. @srish 
Here I'm adding the designs I made with some extra features and details.

The design shows how it will look to a non-user and to a new user.
the added enhancements include-
1. Content changes.
The landing page content should not be text-heavy for the user to ready.
it should be engaging and short.

2. Font size and boldness changes.
The visuals help to focus on other parts of the page too.

3. Adding hamburger menu.
Instead of showing the contacts, about, and other options on the top
we can add that to the menu and focus on the searchbar option as that's
more engaging.

4. Adding an icon to indicate the user is online.
Showing the online state can benefit the user with more engagement.

5. Changing positions of present header assets.
Repositioning of the current header elements to make it more interactive.

6. Changing the signup and Login option.
Instead of using the term sign in I changed it into log in. I also changed
the button option gives more attention on getting started and create
new projects as that will redirect to making an account if the user has
no account.

7. Adding a button to explore present projects.
This will lead to more interaction keep the user interested and also
help the user understand more about how the project works.

![page 1 non user](https://github.com/unstructuredstudio/zubhub/assets/75933388/7e464d74-214f-480d-9345-5f56e3842c38)
![page 2 log in](https://github.com/unstructuredstudio/zubhub/assets/75933388/7439eda9-fede-49ce-83c5-28b192c72f4e)

**Comment by mehreeee** [comment]
@srish This is what I worked on.
1. I made some changes to the Featured project text and section
2. Improved the hero section
a. Improved the search button on the nav bar and added hierarchy to the texts 
4. Improved the Creator review section

I would appreciate a feedback. Thank you.


![Zubhub redesigned landing page](https://github.com/unstructuredstudio/zubhub/assets/105458062/9d78b285-bb26-4b35-91af-5235281f5690)



Link to figma file 
https://www.figma.com/file/yz3GGN7LWgdmNvbnlhhqEw/Zubhub-Landing-page-(Copy)?type=design&node-id=0%3A1&mode=design&t=bIEYCctfOcOGm3KP-1

**Comment by coderatomy** [comment]
nice work @mehreeee. I guess we have to wait @yokwejuste. Everything here looks excellent

**Comment by mehreeee** [comment]
Thank you @coderatomy.

**Comment by GloriaKaduru** [comment]
> nice work @GloriaKaduru. Your designs are really nice

Thank you very much!

**Comment by Marhiposa** [comment]
@srish  I improved the header on zubhub landing page 

- I adjusted the spacing to make things look better and easier to read.
- I organized the text so it flows smoothly, making it simple for visitors to understand.
In the hero section, I replaced the profile logo with a clear 'Sign In' option. This makes it super easy for users to start their journey or access their accounts.
- I made the words in the header sound more fun and catchy. Kids will love it!
still working on the remaining parts let me know what you think @srish 

![updated header](https://github.com/unstructuredstudio/zubhub/assets/146780247/83e9fe89-7185-42bc-83af-0d49f7f32254)

Here is the link to the figma file
(https://www.figma.com/file/9pHe3oGfZUbTh28PXGY15J/Final-ZUBHUB?type=design&node-id=1%3A879&mode=design&t=yiBLFHuxFfPB6ca7-1)

**Comment by Mbeute23** [comment]
Issue: Improve the header design on the landing page

I improve the header design on the landing page by; 

1. Changing the layout of the header

2.  Adjust the search bar to a more simple one

3. Replace the profile and notification with signin and signup button because i belief its when a user will sign in or sign up that the interface for the profile and notification should appear. 

4. Make contrast on the text and giving a tittle to the overall website. 

5. Replacing the project dropdown with home, project, team, review, and about page which will easily make the user to interact fast with what they are looking for. 

Figma link:  https://www.figma.com/file/ByALA1tM5mTZCfLz5Kr3Ko/Outreachy-Zubhub-Design-(Contribution-to-issues)?type=design&node-id=0%3A1&mode=design&t=4UgRB1HUe5y2rx5J-1

![Header design of the landing page_unstructuredstudio](https://github.com/unstructuredstudio/zubhub/assets/146943654/abe278c9-5031-4a32-92e6-2e3eaf9807b3)

@srish Pls for your feedback on the design

**Comment by yokwejuste** [comment]
> nice work @mehreeee. I guess we have to wait @yokwejuste. Everything here looks excellent

Working on this already, cool modifications @mehreeee, I love the modifs you brought 😄

**Comment by mehreeee** [comment]
> > nice work @mehreeee. I guess we have to wait @yokwejuste. Everything here looks excellent
> 
> Working on this already, cool modifications @mehreeee, I love the modifs you brought 😄

Thank you so much🙏  @yokwejuste

**Comment by DonPresh** [comment]
@mehreeee can you improve the spacing for the landing page you designed. I noticed that content from one layer spilled into  other layers. Maybe put each content in frames and the spacing or padding can be 80px.

**Comment by mehreeee** [comment]
> @mehreeee can you improve the spacing for the landing page you designed. I noticed that content from one layer spilled into other layers. Maybe put each content in frames and the spacing or padding can be 80px.

Hi @DonPresh Thank you for the review. I’m fixing it right away

**Comment by Dumzy006** [comment]
Hello @srish 
I worked on this issue : Improve the header on zubhub landing page, adjusting margins, re-arranging text and changing cover image and also "Featured project title having the same size as other title

**I adjusted the margin to have 80px
**Improved the header design 
**Rearranged the hero section tittle and subtitle


See screenshot and figma link below
https://www.figma.com/file/POs8v906c2IFSa7QqDONR6/ZUBHUB-CONTRIBUTION?type=design&node-id=1-139509&mode=design&t=Ami8xziX51xlqbgD-0

![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/0bb24ad6-e02a-4efa-aadc-5303a2eed456)

**Comment by DonPresh** [comment]
I worked on the hero screen and on the featured projects part of the screen, I greyed out the last upload. This is an attempt to draw users to actually signup or login to have access to all the content!
I also made the hero text a little more fun since the target audience are middle, high school students.

**These are my iterations for the screens**:

![Hero page-1](https://github.com/unstructuredstudio/zubhub/assets/100778015/788d0f2d-1a93-4bc3-874c-f966b9ba89dd)
![Hero page](https://github.com/unstructuredstudio/zubhub/assets/100778015/f553d470-7fa6-4526-9871-c00a0577ec65)

https://www.figma.com/file/2twyPjNSSzNEzlMO0doTCb/Outreachy?type=design&node-id=0%3A1&mode=design&t=YeIGl4aGzSdQNBfq-1

@srish @mehreeee please review! Thank you!

**Comment by Marhiposa** [comment]
Hello @srish @tuxology @mehreeee pls what do you think about this improvement?

- [ ] Improved the header on zubhub landing page
- [ ] adjusted margins, re-arranging text and changing cover image. 
- [ ]  Featured project title having the same size as other title
i added a bit of stickers and amount of creators just for credibility, i added a slider for the creator reviews so users can know there are more than one creators. i also change the colour of the header because of the red contrast. 
- [ ] made a transparent button with the label scroll down for user understanding.
 

![Redesigned page](https://github.com/unstructuredstudio/zubhub/assets/146780247/4c020e70-f2b1-43db-bd3a-83b013b68190)

**Comment by coderatomy** [comment]
Great! Nice work all of you guys. Let me hope you have all your mock-ups ready. Nice improvements @Marhiposa

**Comment by srish** [comment]
Thanks a lot, everyone, for your contributions to this task. I loved all your designs. 

I would suggest that we use text for cover page from @Marhiposa's design https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1751603835 and use the design developed by @GloriaKaduru https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1749849546.

@GloriaKaduru Maybe can you replace your text with @Marhiposa's text and share a revised version here for developer's reference? :) 

For developer picking this up, stick to making suggestions requested here https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1749685827

**Comment by brrkrmn** [comment]
Working on this task, 
@GloriaKaduru, waiting for the final version to check if everything matches 🙂

**Comment by yokwejuste** [comment]
> Working on this task, 
> @GloriaKaduru, waiting for the final version to check if everything matches 🙂

Hi 👋, I'm already working on this issue

**Comment by brrkrmn** [comment]
> Hi 👋, I'm already working on this issue

I think we can both work on it @yokwejuste :)

**Comment by yokwejuste** [comment]
> > Hi 👋, I'm already working on this issue
> 
> I think we can both work on it @yokwejuste :)

😌🙌 of course

**Comment by GloriaKaduru** [comment]
> Thanks a lot, everyone, for your contributions to this task. I loved all your designs.
> 
> I would suggest that we use text for cover page from @Marhiposa's design [#792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1751603835) and use the design developed by @GloriaKaduru [#792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1749849546).
> 
> @GloriaKaduru Maybe can you replace your text with @Marhiposa's text and share a revised version here for developer's reference? :)
> 
> For developer picking this up, stick to making suggestions requested here [#792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1749685827)

Sure, I’ll work on that now

**Comment by GloriaKaduru** [comment]
Hi, @srish @yokwejuste @brrkrmn 

Here's the modified version of the design and the link to the design file: https://www.figma.com/file/nyUduEpFmVZ05xA8rt28Mt/ZubHub-Feature-Re-Designs?type=design&node-id=12%3A1901&mode=design&t=lQ3hMKDoJEbcTdlT-1


![New Header design for Landing Page](https://github.com/unstructuredstudio/zubhub/assets/82684587/fbd9bc90-69a0-4d13-87d9-c4a3dcf0e86a)

**Comment by yokwejuste** [comment]
> Hi, @srish @yokwejuste @brrkrmn
> 
> Here's the modified version of the design and the link to the design file: https://www.figma.com/file/nyUduEpFmVZ05xA8rt28Mt/ZubHub-Feature-Re-Designs?type=design&node-id=12%3A1901&mode=design&t=lQ3hMKDoJEbcTdlT-1
> 
> ![New Header design for Landing Page](https://user-images.githubusercontent.com/82684587/274298271-fbd9bc90-69a0-4d13-87d9-c4a3dcf0e86a.png)

Great job @GloriaKaduru, now I've a suggestion to make, when designing if you for the 3 basic screen sizes i.e. desktop, tablet, mobile so we can  easily implement a good responsive page when the design is accepted.

**Comment by Marhiposa** [comment]
> Thanks a lot, everyone, for your contributions to this task. I loved all your designs.
> 
> I would suggest that we use text for cover page from @Marhiposa's design [#792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1751603835) and use the design developed by @GloriaKaduru [#792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1749849546).
> 
> @GloriaKaduru Maybe can you replace your text with @Marhiposa's text and share a revised version here for developer's reference? :)
> 
> For developer picking this up, stick to making suggestions requested here [#792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1749685827)

Thanks

**Comment by aqsaaqeel** [comment]
I have raised a PR in #883  that implements the finalized design by @GloriaKaduru I did not have access to hero table in database so I had to populate it on http://localhost:8000/admin So in order to view the changes in PR we ca do the same.
cc: @srish @tuxology

**Comment by coderatomy** [comment]
Nice work everyone. Who is taking action on this

**Comment by aqsaaqeel** [comment]
> Nice work everyone. Who is taking action on this

I have raised a PR for this at #883 @coderatomy

**Comment by tuxology** [comment]
@srish and @aqsaaqeel So I was going through these designs. While I agree partially with your comment https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1756589431 I still feel that after seeing the implementation on #883  the visuals don't really look that great. I think the hero elements needs to show bold text and large images. In that perspective, I like the styling of @GloriaKaduru here https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1757754802 Also, just a reminder to everyone here - while your suggestions are awesome, **we are only focusing on the hero element** for the scope of this work for now. 

Request to @aqsaaqeel Can you update the PR https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1753295577 with the following changes:
 - User design here https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1757754802 (only hero element)
 - The color of "Share!" can remain white
 - Keep fonts same as those on Zubhub right now

**Comment by aqsaaqeel** [comment]
> @srish and @aqsaaqeel So I was going through these designs. While I agree partially with your comment [#792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1756589431) I still feel that after seeing the implementation on #883 the visuals don't really look that great. I think the hero elements needs to show bold text and large images. In that perspective, I like the styling of @GloriaKaduru here [#792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1757754802) Also, just a reminder to everyone here - while your suggestions are awesome, **we are only focusing on the hero element** for the scope of this work for now.
> 
> Request to @aqsaaqeel Can you update the PR [#792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1753295577) with the following changes:
> 
> * User design here [Improve the header design on the landing page #792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1757754802) (only hero element)
> * The color of "Share!" can remain white
> * Keep fonts same as those on Zubhub right now

Thanks for the feedback, I am working on it now!

**Comment by aqsaaqeel** [comment]
> @srish and @aqsaaqeel So I was going through these designs. While I agree partially with your comment [#792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1756589431) I still feel that after seeing the implementation on #883 the visuals don't really look that great. I think the hero elements needs to show bold text and large images. In that perspective, I like the styling of @GloriaKaduru here [#792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1757754802) Also, just a reminder to everyone here - while your suggestions are awesome, **we are only focusing on the hero element** for the scope of this work for now.
> 
> Request to @aqsaaqeel Can you update the PR [#792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1753295577) with the following changes:
> 
> * User design here [Improve the header design on the landing page #792 (comment)](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1757754802) (only hero element)
> * The color of "Share!" can remain white
> * Keep fonts same as those on Zubhub right now

I have made the changes in #883 as you suggested @tuxology

**Comment by Boluwatifey1** [comment]
Hi @srish and @tuxology when I opened the Zubhub website I figured out there is no navigation bar, if you want to access the About page you would need to go all the way down to the footer and this is a bad experience for the user, so I added nav bar to the header, also the landing page lacks hierarchy,(the text need to be emphasized on to come out boldly and clearly) and the CTA button lacks padding and I think the red color background is too sharp. 
how it looks on the website:
![zub hub home page](https://github.com/unstructuredstudio/zubhub/assets/127180289/3bd6eb0d-d5f6-482d-baac-033cb7e24c1c)

this is what I  came up with:
![home -_unstructuredstudio (2)](https://github.com/unstructuredstudio/zubhub/assets/127180289/23108f84-3cf5-4f1e-a7d5-77cb4b147a31)

kindly  review it

**Comment by coderatomy** [comment]
Nice work everyone
