### ISSUE TITLE
Allow users change/Edit their profile picture

### ISSUE THREAD

**Issue by JulietMadu** [unstructuredstudio/zubhub#837]
there should be a feature that allow users edit their profile image to either available avartar to select from or an image of them.

@srish i can work on this issue

**Comment by Boluwatifey1** [comment]
@JulietMadu I agree with you and I have also come up with some designs, if I am allowed @srish I would love to drop some ideas on this

**Comment by Boluwatifey1** [comment]
Good day @srish @tuxology I added a "change photo" feature to the edit profile page, which gives user access to edit their profile picture, either by choosing an avatar, uploading a picture, or choosing to delete the current picture, I noticed that the profile picture icon is not responsive  and I also added a field box for "New Password" on the same page because I noticed that there is only a "Current Password" field box there is none for when you decide to change your
password

This is how it looks on the website 
![old edit profile page](https://github.com/unstructuredstudio/zubhub/assets/127180289/f2ee50e1-68af-4ee8-9d57-9474c8aff76e)

so this is how it looks when I added the change photo feature and the "New Password "field box
![add Profile picture](https://github.com/unstructuredstudio/zubhub/assets/127180289/b88cab9c-89ea-48e3-a3e7-8f249153a84a)
 So I came up with two options for the page that pops up when you click on the Change photo feature
in the first option, I added three icons below the current profile picture which is the default photo when you sign up

**1** I added a "camera icon" which serves as the choose photo from library/ browse photo option 
**2**  I added  the "comic icon" which serves as use avatar option that would allow you to pick from a list of already made avatars
**3** Lastly I Introduced the "delete icon" which allows you to delete your current profile photo.

this is how it looks
![add Profile picture (5)](https://github.com/unstructuredstudio/zubhub/assets/127180289/20e58e7d-c9fa-4e85-9990-392adb570edf)


For the second option, I replaced the options with text for a better understanding, this is how it looks:
![add Profile picture (4)](https://github.com/unstructuredstudio/zubhub/assets/127180289/79f8188f-6f12-4996-9496-6a2a35d55bed)


 both screens have a previous page feature at the bottom end that would take you back to the edit profile page.  I can make it look better if I am given permission to carry on and @JulietMadu can also add her contributions

**Comment by JulietMadu** [comment]
nice one @Boluwatifey1 , i was able to design the mobile screen and i also included some avatars that can be used as profile pictures @srish 
![Screenshot (216)](https://github.com/unstructuredstudio/zubhub/assets/128796937/27ec6873-00aa-4295-b4d2-5f6d3047bdfc)

**Comment by Adaking-slack** [comment]
> Good day @srish @tuxology I added a "change photo" feature to the edit profile page, which gives user access to edit their profile picture, either by choosing an avatar, uploading a picture, or choosing to delete the current picture, I noticed that the profile picture icon is not responsive and I also added a field box for "New Password" on the same page because I noticed that there is only a "Current Password" field box there is none for when you decide to change your password
> 
> This is how it looks on the website ![old edit profile page](https://user-images.githubusercontent.com/127180289/273421469-f2ee50e1-68af-4ee8-9d57-9474c8aff76e.jpg)
> 
> so this is how it looks when I added the change photo feature and the "New Password "field box ![add Profile picture](https://user-images.githubusercontent.com/127180289/273421325-b88cab9c-89ea-48e3-a3e7-8f249153a84a.png) So I came up with two options for the page that pops up when you click on the Change photo feature in the first option, I added three icons below the current profile picture which is the default photo when you sign up
> 
> **1** I added a "camera icon" which serves as the choose photo from library/ browse photo option **2** I added the "comic icon" which serves as use avatar option that would allow you to pick from a list of already made avatars **3** Lastly I Introduced the "delete icon" which allows you to delete your current profile photo.
> 
> this is how it looks ![add Profile picture (5)](https://user-images.githubusercontent.com/127180289/273422918-20e58e7d-c9fa-4e85-9990-392adb570edf.png)
> 
> For the second option, I replaced the options with text for a better understanding, this is how it looks: ![add Profile picture (4)](https://user-images.githubusercontent.com/127180289/273422312-79f8188f-6f12-4996-9496-6a2a35d55bed.png)
> 
> both screens have a previous page feature at the bottom end that would take you back to the edit profile page. I can make it look better if I am given permission to carry on and @JulietMadu can also add her contributions

Hi, this looks really good, I suggest that the change photo icon and label on your first design should be in the middle, instaed of the far right for a better UI, and the change photo label should be black(or any other color that goes with the color scheme of the page) instead of blue,

**Comment by Boluwatifey1** [comment]
> > Good day @srish @tuxology I added a "change photo" feature to the edit profile page, which gives user access to edit their profile picture, either by choosing an avatar, uploading a picture, or choosing to delete the current picture, I noticed that the profile picture icon is not responsive and I also added a field box for "New Password" on the same page because I noticed that there is only a "Current Password" field box there is none for when you decide to change your password
> > This is how it looks on the website ![old edit profile page](https://user-images.githubusercontent.com/127180289/273421469-f2ee50e1-68af-4ee8-9d57-9474c8aff76e.jpg)
> > so this is how it looks when I added the change photo feature and the "New Password "field box ![add Profile picture](https://user-images.githubusercontent.com/127180289/273421325-b88cab9c-89ea-48e3-a3e7-8f249153a84a.png) So I came up with two options for the page that pops up when you click on the Change photo feature in the first option, I added three icons below the current profile picture which is the default photo when you sign up
> > **1** I added a "camera icon" which serves as the choose photo from library/ browse photo option **2** I added the "comic icon" which serves as use avatar option that would allow you to pick from a list of already made avatars **3** Lastly I Introduced the "delete icon" which allows you to delete your current profile photo.
> > this is how it looks ![add Profile picture (5)](https://user-images.githubusercontent.com/127180289/273422918-20e58e7d-c9fa-4e85-9990-392adb570edf.png)
> > For the second option, I replaced the options with text for a better understanding, this is how it looks: ![add Profile picture (4)](https://user-images.githubusercontent.com/127180289/273422312-79f8188f-6f12-4996-9496-6a2a35d55bed.png)
> > both screens have a previous page feature at the bottom end that would take you back to the edit profile page. I can make it look better if I am given permission to carry on and @JulietMadu can also add her contributions
> 
> Hi, this looks really good, I suggest that the change photo icon and label on your first design should be in the middle, instaed of the far right for a better UI, and the change photo label should be black(or any other color that goes with the color scheme of the page) instead of blue,

Okay thank you for the suggestion but there is little space in the middle ,could only be in the middle on the mobile interface like @JulietMadu did but I would work on the color

**Comment by Boluwatifey1** [comment]
@Adaking-slack I was able to work on those issues you mentioned, so this is how it looks now
![add Profile picture (6)](https://github.com/unstructuredstudio/zubhub/assets/127180289/41610198-d14c-4344-85df-9f5a6ad83c34)
if there is any further corrections, kindly let me know. Thanks

**Comment by Adaking-slack** [comment]
> @Adaking-slack I was able to work on those issues you mentioned, so this is how it looks now ![add Profile picture (6)](https://user-images.githubusercontent.com/127180289/273784368-41610198-d14c-4344-85df-9f5a6ad83c34.png) if there is any further corrections, kindly let me know. Thanks

hi, yes this looks good 😊

**Comment by srish** [comment]
Changing the profile picture is out of scope due to privacy reasons. We don't want anyone to upload custom photos. That's why we have kept this issue out of scope. Thanks for providing your suggestions.

**Comment by JulietMadu** [comment]
> Changing the profile picture is out of scope due to privacy reasons. We don't want anyone to upload custom photos. That's why we have kept this issue out of scope. Thanks for providing your suggestions.

I understand about the privacy issues,  but changing of avatar images can still be added incase a user is given an avatar he/she doesn't like. They should be allowed to select from available avartars . @srish

**Comment by JulietMadu** [comment]
here are sample images of avartars i meant @srish 
![Uploading avartars.png…]()

**Comment by JulietMadu** [comment]
![avartars](https://github.com/unstructuredstudio/zubhub/assets/128796937/256cf0fa-0047-4f68-840d-4d51153e35a3)
