### ISSUE TITLE
Navbar does not show user's avatar when logged in

### ISSUE THREAD

**Issue by aqsaaqeel** [unstructuredstudio/zubhub#945]
**Describe the bug**
Right now there is a placeholder avatar on the navbar. It does not display the user's avatar even when logged in.

**To Reproduce**

1. Login on Zubhub.
2. Notice the avatar icon

**Expected behavior**
The avatar icon must show the user's avatar when the user is logged in. But it shows a placeholder icon instead.

**Screenshots**

![Screenshot from 2023-10-23 20-12-23](https://github.com/unstructuredstudio/zubhub/assets/85514520/d458f330-2912-475b-8264-27246fd762fc)

We must see this avatar on the navbar too

![Screenshot from 2023-10-23 20-14-32](https://github.com/unstructuredstudio/zubhub/assets/85514520/ec65f526-ba94-468b-b33f-95831cf8d516)

**Comment by Marhiposa** [comment]
Hi @aqsaaqeel @srish  

I fixed the navbar showing the avatar when logged in. 

![Navbar](https://github.com/unstructuredstudio/zubhub/assets/146780247/caba2cae-c4cc-40fc-b253-018740d2ccc8)

**Comment by aqsaaqeel** [comment]
Hey @Marhiposa I have made the fixes in #946 could you take a look and see if it looks fine?

**Comment by Michelle-okechi** [comment]
Hello @srish i made some design variations on the Profile avatar. Please which do you prefer?

The is a state for when the users haven't uploaded their own picture. I used this avatar because of it gives a human notation instead of a robot.

![blue avatar](https://github.com/unstructuredstudio/zubhub/assets/146777024/a3a74f23-44e3-4a33-99a0-8d7cb2aa67ee)

The second state shows indicates what the avatar would like when users upload their pictures

![with pic](https://github.com/unstructuredstudio/zubhub/assets/146777024/0767f437-c136-4414-93d7-5164b7c245bd)

**Comment by pachougu** [comment]
Hello @srish I made this design 
![drafts - drafts view_unstructuredstudio](https://github.com/unstructuredstudio/zubhub/assets/146971182/07de61d0-5ea4-45f1-a45c-21143bbcf038)
![drafts - drafts view_unstructuredstudio-1](https://github.com/unstructuredstudio/zubhub/assets/146971182/15fc78e7-c2dd-430c-813c-b7d60e78defd)

**Comment by Marhiposa** [comment]
> Hey @Marhiposa I have made the fixes in #946 could you take a look and see if it looks fine?

hi @aqsaaqeel its still showing the placeholder when logged in.
